"""empty message

Revision ID: 47cebbd1841b
Revises: 6a8cf42bf0a3
Create Date: 2022-12-01 15:47:13.013785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "47cebbd1841b"
down_revision = "6a8cf42bf0a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    currency = postgresql.ENUM(
        "dollar", "pound", "euro", name="currency", create_type=False, nullable=False
    )
    currency.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "currency",
            sa.Enum("dollar", "pound", "euro", name="currency"),
            nullable=True,
        ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "currency")

    currency = postgresql.ENUM(
        "dollar", "pound", "euro", name="currency", create_type=False, nullable=False
    )
    currency.drop(op.get_bind())

    # ### end Alembic commands ###
