"""settings

Revision ID: 6a8cf42bf0a3
Revises: d421787e7ad6
Create Date: 2022-11-28 13:09:27.955915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6a8cf42bf0a3"
down_revision = "d421787e7ad6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sheets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    metricsystem = postgresql.ENUM(
        "centimeter", "inch", name="metricsystem", create_type=False, nullable=False
    )
    metricsystem.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "metric_system",
            sa.Enum("centimeter", "inch", name="metricsystem"),
            nullable=True,
        ),
    )
    op.add_column("users", sa.Column("print_price", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("is_price_per_sheet", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("moq", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("cut_spacing", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("is_enabled_buy_btn", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("buy_url", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "buy_url")
    op.drop_column("users", "is_enabled_buy_btn")
    op.drop_column("users", "cut_spacing")
    op.drop_column("users", "moq")
    op.drop_column("users", "is_price_per_sheet")
    op.drop_column("users", "print_price")
    op.drop_column("users", "metric_system")
    op.drop_table("sheets")

    metricsystem = postgresql.ENUM(
        "centimeter", "inch", name="metricsystem", create_type=False, nullable=False
    )
    metricsystem.drop(op.get_bind())
    # ### end Alembic commands ###
