"""empty message

Revision ID: 71d3cb2dbedc
Revises: 7f17fafb5f70
Create Date: 2023-01-30 12:42:33.506360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d3cb2dbedc'
down_revision = '7f17fafb5f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shop_name')
    # ### end Alembic commands ###
