"""empty message

Revision ID: 7e5ed84e72c5
Revises: 7e60c0096ba1
Create Date: 2022-11-11 21:11:28.187811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5ed84e72c5'
down_revision = '7e60c0096ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_code', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recovery_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_recovery')
    # ### end Alembic commands ###
