"""empty message

Revision ID: 7e60c0096ba1
Revises: 0f35a16ff79a
Create Date: 2022-11-11 13:03:57.309517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e60c0096ba1'
down_revision = '0f35a16ff79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmation_token', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['confirmation_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'confirmation_token')
    # ### end Alembic commands ###
