"""empty message

Revision ID: 8958a7981061
Revises: 59534c255589
Create Date: 2023-02-03 14:10:52.757867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8958a7981061"
down_revision = "59534c255589"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("logo_img", sa.Text(), nullable=True))
    op.add_column(
        "users", sa.Column("logo_file_name", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "logo_file_name")
    op.drop_column("users", "logo_img")
    # ### end Alembic commands ###
