"""empty message

Revision ID: 8b6c73daaf4c
Revises: 47cebbd1841b
Create Date: 2022-12-02 11:54:56.729188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b6c73daaf4c"
down_revision = "47cebbd1841b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sheets", sa.Column("price", sa.Float(), nullable=True, server_default=0)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sheets", "price")
    # ### end Alembic commands ###
