"""empty message

Revision ID: a0dd84808e5e
Revises: abb5e84e81df
Create Date: 2022-11-14 12:22:04.862251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0dd84808e5e'
down_revision = 'abb5e84e81df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_recovery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recovery_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='password_recovery_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_recovery_pkey'),
    sa.UniqueConstraint('recovery_code', name='password_recovery_recovery_code_key')
    )
    # ### end Alembic commands ###
