"""empty message

Revision ID: ba5238eac1b7
Revises: 8958a7981061
Create Date: 2023-02-03 15:21:44.067829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5238eac1b7'
down_revision = '8958a7981061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logo_file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logo_file_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
