"""sheet moq

Revision ID: bf87a25d315f
Revises: 8b6c73daaf4c
Create Date: 2022-12-05 16:06:31.218516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf87a25d315f'
down_revision = '8b6c73daaf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheets', sa.Column('moq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheets', 'moq')
    # ### end Alembic commands ###
