"""empty message

Revision ID: d421787e7ad6
Revises: 0f35a16ff79a
Create Date: 2022-11-14 16:52:27.609562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd421787e7ad6'
down_revision = '0f35a16ff79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reset_password_uid', sa.String(length=64), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'reset_password_uid')
    op.drop_column('users', 'deleted')
    # ### end Alembic commands ###
